apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.sidecar.telemetry.volumes.host.persistentVolumeClaimName }}
  name: {{ .Values.sidecar.telemetry.volumes.host.persistentVolumeClaimName }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}